apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-setup-test-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /path/to/nfs/export
    server: nfs-server.example.com
