---
- name: Installing Docker, AWS Cli & Jenkins
  hosts: linux
  become: yes
  tasks:
    - name: Installing Docker, AWS Cli & Jenkins
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
        apt update -y
        apt install openjdk-17-jre -y
        wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
        apt-get update -y
        apt-get install jenkins -y
        apt install docker.io -y
        usermod -aG docker $USER
        chmod 666 /var/run/docker.sock
      args:
        executable: /bin/bash
